version: '3'
services:
  backend:
    image: dimmaryanto93/udemy-springboot-app:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: <ip-domain-db>
      DATABASE_PORT: 5432
      DATABASE_NAME: <db-name>
      DATABASE_PASSWORD: <db-password>
      APPLICATION_PORT: 8080

  frontend:
    image: dimmaryanto93/udemy-angular-app:latest
    ports:
      - "80:80"
    environment:
      APPLICATION_PORT: 80
      NGINX_ROOT_DOCUMENT: /var/www/html
      BACKEND_HOST: <ip-backend-apps>
      BACKEND_PORT: <port-backend-apps>
      BACKEND_CONTEXT_PATH: /
